'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IMSS_Browser_Cleaner.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _IMSS_Browsers_Icon_155x147() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Browsers_Icon_155x147", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_BrowsersCleanup_Icon_155x147() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_BrowsersCleanup_Icon_155x147", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Chrome_Icon_16x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Chrome_Icon_16x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Complete_Icon_140x140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Complete_Icon_140x140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_EmergencyTap_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_EmergencyTap_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Folder_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Folder_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_InternetExplorer_Icon_16x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_InternetExplorer_Icon_16x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_ListItems_Icon_48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ListItems_Icon_48x48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_MozillaFireFox_Icon_16x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_MozillaFireFox_Icon_16x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Opera_Icon_16x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Opera_Icon_16x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Other_Icon_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Other_Icon_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_ProcessingWarning_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ProcessingWarning_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_Safari_Icon_16x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Safari_Icon_16x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_StatusOn_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_StatusOn_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _IMSS_TemporaryFile_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_TemporaryFile_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMSS_Onerror_Cleaner() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_Onerror_Cleaner", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property IMSS_Onerror_Cleaner_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_Onerror_Cleaner_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
